language: node_js

branches:
  only: master

install:
- cd _scripts/
- npm install
- cd ..

script:
- node ./_scripts/main.js
- jekyll build --destination /var/www/html/richardbright.me

notifications:
  email:
    on_success: never
    on_failure: always
